import { resolve } from 'node:path';
import { migrate } from 'drizzle-orm/node-postgres/migrator';
import { loadEnv } from '../../../config/env';
import { createDatabase } from './client';

/**
 * Applies the SQL migrations generated by `pnpm db:generate`.
 *
 * Migrations are files under `apps/api/drizzle`, produced offline from the
 * TypeScript schema and reviewable in a pull request — as opposed to
 * `drizzle-kit push`, which mutates a database from the schema directly and is
 * only appropriate on a local machine.
 */
/* c8 ignore start -- CLI entry point. */
async function main(): Promise<void> {
  const env = loadEnv();
  if (!env.DATABASE_URL) throw new Error('DATABASE_URL is required to migrate.');

  const { db, pool } = createDatabase(env.DATABASE_URL);
  try {
    await migrate(db as never, { migrationsFolder: resolve(process.cwd(), 'drizzle') });
    console.log('Migraciones aplicadas.');
  } finally {
    await pool.end();
  }
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
/* c8 ignore stop */
